name: CI
env:
  MIRRORD_TELEMETRY: false

permissions:
  contents: read

on:
  merge_group:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, staging, trying ]
    types: [ opened, synchronize, reopened, ready_for_review ]

# Cancel previous runs on the same PR.
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  towncrier_check:
    if: github.event_name != 'pull_request' || github.event.pull_request.user.login != 'dependabot[bot]'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
      - run: uv python install
      - run: uv venv
      - name: install towncrier
        run: uv pip install towncrier==23.11.0
      - name: verify newsfragment exist
        run: uv run towncrier check

  lint_markdown:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: metalbear-co/markdownlint-cli2-action@0fb2cca662f67f99dfdb04fce7d81bb2904ee404
        with:
          config: ".markdownlint.json"
          globs: "README.md"

  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: zulu
          java-version: 21
      - name: Run ktlint
        run: ./gradlew ktlintCheck

  e2e:
    uses: ./.github/workflows/reusable_e2e.yaml

  ci-success:
    name: ci
    # We want this to run even if some of the required jobs got skipped
    if: always()
    needs:
      [
        towncrier_check,
        e2e,
        lint_markdown,
        lint,
      ]
    runs-on: ubuntu-24.04
    steps:
      - name: CI succeeded
        # We have to do it in the shell since if it's in the if condition
        # then skipping is considered success by branch protection rules
        env:
          CI_SUCCESS: ${{ (needs.towncrier_check.result == 'success' || needs.towncrier_check.result == 'skipped') &&
            (needs.e2e.result == 'success' || needs.e2e.result == 'skipped') &&
            (needs.lint_markdown.result == 'success' || needs.lint_markdown.result == 'skipped') &&
            (needs.lint.result == 'success' || needs.lint.result == 'skipped') }}
        run: echo "$CI_SUCCESS" && if [ "$CI_SUCCESS" == "true" ]; then echo "SUCCESS" && exit 0; else echo "Failure" && exit 1; fi
