name: Release
on:
  push:
    tags:
      - "*.*.*"
  # Running from workflow dispatch (AKA manual) will not publish anything.
  # This is intended for testing changes to this flow.
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        id: version
      - name: get custom delve
        run: |
          mkdir -p bin/macos/arm64
          mkdir -p bin/macos/x86-64
          wget https://github.com/metalbear-co/delve/releases/download/1.20.1/delve_darwin_arm64 -O bin/macos/arm64/dlv
          wget https://github.com/metalbear-co/delve/releases/download/1.20.1/delve_darwin_amd64 -O bin/macos/x86-64/dlv
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
      - name: Build Plugin
        run: |
          chmod +x ./gradlew
          ./gradlew buildPlugin
      - name: Publish Plugin
        if: github.event_name != 'workflow_dispatch'
        env:
          PUBLISH_TOKEN: ${{ secrets.INTELLIJ_PUBLISH_TOKEN }}
          CERTIFICATE_CHAIN: ${{ secrets.INTELLIJ_CERTIFICATE_CHAIN }}
          PRIVATE_KEY: ${{ secrets.INTELLIJ_PRIVATE_KEY }}
          PRIVATE_KEY_PASSWORD: ${{ secrets.INTELLIJ_PRIVATE_KEY_PASSWORD }}
        run: |
          chmod +x ./gradlew
          ./gradlew publishPlugin
      - uses: actions/upload-artifact@v4
        with:
          name: intellij-ext
          path: build/distributions/*.zip
          if-no-files-found: error

  release_gh:
    needs: [release]
    runs-on: ubuntu-24.04
    if: github.event_name != 'workflow_dispatch'
    permissions:
      packages: write
      contents: write
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: /tmp/artifacts
      - name: Prepare binaries for upload
        run: |
          mkdir /tmp/release
          mv /tmp/artifacts/intellij-ext/* /tmp/release/

      # Consider to add changelog generation..
      - name: Release
        uses: metalbear-co/action-gh-release@ab50eebb6488051c6788d97fa95232267c6a4e23
        with:
          files: /tmp/release/**

  update_latest:
    needs: release_gh
    runs-on: ubuntu-24.04
    if: github.event_name != 'workflow_dispatch'
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          # Get complete history
          fetch-depth: 0

      - name: Update major version and latest tags
        uses: metalbear-co/release-tracker-action@main
        env:
          # GitHub token to enable pushing tags
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Move "latest" tag
          update-latest: true
          # Don't update the vX.Y tags
          update-minor: false
