# This is a reusable workflow that can be run based on `mirrord_release_branch` boolean input
# in the `mirrord` or `mirrord-intellij` repository and hence is maintained in a single place.
# The difference in the workflow when `mirrord_release_branch` is set is as follows:
# - we checkout into the latest released tag of `mirrord-intellij` from the perspective of binary
# that has to be released on `mirrord` side. if not set, we checkout into the current branch.
# - we rely on downloading the mirrord binary from `mirrord-artifacts` using `actions/download-artifact`
# and adding it to the path. if not set, the latest version is downloaded.

name: reusable_e2e
on:
  workflow_call:
    inputs:
      mirrord_release_branch:
        required: false
        type: boolean
        default: false

jobs:
  intellij-e2e:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    env:
      CI_BUILD_PLUGIN: "true"
    steps:

      - name: Free Disk Space (Ubuntu)
        uses: metalbear-co/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # default branch HEAD
        with:
          # this might remove tools that are actually needed,
          # if set to "true", frees about 6 GB
          tool-cache: false

      - name: checkout repository
        if: ${{ !inputs.mirrord_release_branch }}
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

        # mirrord_release_branch boolean when set, means we are on a release branch
        # and hence we need to checkout into the last released tag of mirrord-intellij
      - name: checkout into mirrord-intellij if mirrord_release_branch
        if: ${{ inputs.mirrord_release_branch }}
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: "metalbear-co/mirrord-intellij"

      - name: checkout into the last released tag if mirrord_release_branch
        if: ${{ inputs.mirrord_release_branch }}
        run: |
          git fetch --all --tags
          git checkout tags/$(grep 'pluginVersion =' gradle.properties | cut -d '=' -f 2 | xargs)

      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: zulu
          java-version: 17

      - name: build plugin
        run: |
          ./gradlew buildPlugin


      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: 3.11
      - uses: metalbear-co/actions-poetry@b8f6fe29ba2eb78e0d45ccbf41cd14154c4e25b2

        # we are on a release branch, so we need to download the mirrord binary from
        # mirrord-artifacts and add it to the path
      - name: download mirrord binary
        if: ${{ inputs.mirrord_release_branch }}
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: mirrord-artifacts
      - name: add downloaded mirrord to path
        if: ${{ inputs.mirrord_release_branch }}
        run: |
          chmod u+x mirrord
          echo "${GITHUB_WORKSPACE}" >> $GITHUB_PATH

      - name: get the latest mirrord binary
        if: ${{ !inputs.mirrord_release_branch }}
        run: |
          curl -fsSL https://raw.githubusercontent.com/metalbear-co/mirrord/main/scripts/install.sh | bash

      - name: Start minikube
        uses: metalbear-co/setup-minikube@3fa06c2257eb48a3ca8e24fedece59ee2479255a
        with:
          container-runtime: docker
      - run: |
          kubectl apply -f sample/kubernetes/app.yaml
          echo "POD_TO_SELECT=$(kubectl get pods -o=name | head -n 1)" >> "$GITHUB_ENV"
          kubectl wait --for=condition=ready --timeout=30s $(kubectl get pods -o=name | head -n 1)
          KUBE_SERVICE=$(minikube service list --output=json | jq -r '.[] | select(.Name == "py-serv") | .URLs[0]')
          echo "$KUBE_SERVICE"
          echo "KUBE_SERVICE=$KUBE_SERVICE" >> "$GITHUB_ENV"

      - name: download image
        if: ${{ inputs.mirrord_release_branch }}
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: test
          path: /tmp
      - run: minikube image load /tmp/test.tar
        if: ${{ inputs.mirrord_release_branch }}

      - name: Run intellij e2e in headless state
        if: ${{ inputs.mirrord_release_branch }}
        env:
          POD_TO_SELECT: ${{ env.POD_TO_SELECT }}
          KUBE_SERVICE: ${{ env.KUBE_SERVICE }}
          MIRRORD_AGENT_IMAGE: "test"
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb x11-xserver-utils ffmpeg
          /usr/bin/xvfb-run -s ":99 -auth /tmp/xvfb.auth -ac -screen 0 1920x1080x24" ./gradlew test &
          ffmpeg -loglevel panic -y -framerate 30 -f x11grab -video_size 1920x1080 -i :99 out.webm
          wait -n

      - name: Run intellij e2e in headless state
        if: ${{ !inputs.mirrord_release_branch }}
        env:
          POD_TO_SELECT: ${{ env.POD_TO_SELECT }}
          KUBE_SERVICE: ${{ env.KUBE_SERVICE }}
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb x11-xserver-utils ffmpeg
          /usr/bin/xvfb-run -s ":99 -auth /tmp/xvfb.auth -ac -screen 0 1920x1080x24" ./gradlew test &
          ffmpeg -loglevel panic -y -framerate 30 -f x11grab -video_size 1920x1080 -i :99 out.webm
          wait -n

      - name: Save the failure video
        continue-on-error: true
        if: ${{ always() }}
        run: |
          mv video build/reports
      - name: Save fails report
        if: ${{ failure() }}
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: mirrord-plugin-fail-report
          path: |
            build/reports
